### PR TITLE
Update v3.0.0alpha3

### PR DESCRIPTION
**Pull request by Tata17**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Tata17** [comment]
@conda-forge-admin please rerender

**Comment by ocefpaf** [comment]
Looks like 22 tests are failing and I'm not sure if the problem is related to our build system. Maybe we should ask upstream about it.

**Comment by Tata17** [comment]
> Looks like 22 tests are failing and I'm not sure if the problem is related to our build system. Maybe we should ask upstream about it.

What do you mean ask upstream?

**Comment by Tata17** [comment]
Also, now the error (after adding libxslt) seems to be a topology error, similar to https://github.com/conda-forge/postgis-feedstock/pull/25

**Comment by ocefpaf** [comment]
Closing this in favor of #25

**Pull request closed without merging**
