### PR TITLE
Rebuild for proj-6.2.1

### PR DESCRIPTION
**Pull request by xylar**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
I got a little over eager.  GDAL isn't there yet.

**Comment by hobu** [comment]
The conflict is confusing (and has been there a while).

```
libgdal=3.0 -> libuuid[version='>=2.32.1,<3.0a0']
postgresql -> libuuid=1.0
```

Does this mean that the postgresql feedstock needs to be bumped to catch a newer libuuid?

**Comment by xylar** [comment]
@hobu, my experience is that these conflict reports are not usually very helpful.  I think the problem is actually that the `gdal` rebuild hasn't finished yet and the new versions aren't yet available on `conda-forge` but the solver found a set of packages that it thinks would work except for this conflict with `libuuid`.  I think that's not the path we would want to take so the error just isn't very helpful.

I usually debug these kinds of things by using `conda create` and just adding libraries one by one until the conflict emerges (usually with a more helpful message about the conflict).  It's tedious but gets me where I need to be, whereas these default conflict reports are nearly always totally useless to me.

**Comment by xylar** [comment]
@sodre or @dwnoble, I think we're good here.  Please merge if you're okay with the rebuild for the latest `proj`.

**Pull request merged**
