### PR TITLE
add new maintainer

### PR DESCRIPTION
**Pull request by rluria14**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
@rluria14, I would be uncomfortable adding `mxr-conda` as a maintainer unless that account is actually issuing the PR requesting to be added.

**Comment by xylar** [comment]
That being said, we clearly do need some help maintaining the feedstock.  Do you have thoughts on how to get the OSX build working again?

**Comment by rluria14** [comment]
Agree with being a maintainer.

**Comment by mxr-conda** [comment]
@xylar agree with being a maintainer

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
@rluria14 and @mxr-conda, I don't seem to be able to rerender.  I don't think I (as a maintainer) or the bot have permission to alter the branch.  Without that, it's no good to merge the PR because you won't actually get added as a maintainer.

**Comment by xylar** [comment]
I can do it myself, though.  Just a sec.

**Comment by xylar** [comment]
I think the problem is that this fork got deleted before the PR got merged.

**Pull request closed without merging**
